---
version: "2"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - ${JACKETT_CONFIG_FOLDER}:/config
      - ${JACKETT_DOWNLOADS_FOLDER}:/downloads
    ports:
      - 9117:9117
    expose:
      - 9117
    restart: unless-stopped
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
      - UMASK_SET=002
      - WEBUI_PORT=8888
      - PASSWORD=${QBITTORRENT_PASSWORD}
    volumes:
      - ${QBITTORRENT_CONFIG_FOLDER}:/config
      - ${QBITTORRENT_DOWNLOADS_FOLDER}:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8888:8888
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
      - UMASK_SET=022
    volumes:
      - ${RADARR_CONFIG_FOLDER}:/config
      - ${RADARR_MOVIES_FOLDER}:/movies
      - ${RADARR_TORRENT_CLIENT_OUTPUT}:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
      - UMASK_SET=020
    volumes:
      - ${SONARR_CONFIG_FOLDER}:/config
      - ${SONARR_TV_FOLDER}:/tv
      - ${SONARR_TORRENT_CLIENT_OUTPUT}:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
